import type { Metadata } from 'next';
import Link from 'next/link';
import { Container, NominationCTA } from '@/components/primitives';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { RulesNavigation } from './rules-navigation';
import groups from './criteria.json';
import '../home.css';
import './rules.css';
export const metadata: Metadata = {title:'Thể lệ — Travel Awards 2026',description:'Hạng mục, đối tượng, thời gian tổ chức và tiêu chí đánh giá Travel Awards 2026.'};
const phases=[['Tháng 10/2026','Ra mắt & nhận đề cử','Giới thiệu Travel Awards, công bố hệ thống giải thưởng và mở cổng nhận đề cử sơ loại.'],['Tháng 11 – 12/2026','Bình chọn & đánh giá','Đóng cổng nhận đề cử, mở cổng bình chọn và triển khai đánh giá các hạng mục giải thưởng.'],['Tháng 12/2026 – 1/2027','Hoạt động đồng hành','Triển khai Social Challenge và các hoạt động lan tỏa hành trình Travel Awards.'],['Tháng 1/2027','Diễn đàn & Gala trao giải','Tổ chức diễn đàn du lịch, Gala trao giải; công bố kết quả và cập nhật tư liệu sự kiện.']];
function Title({number,children}:{number:string;children:React.ReactNode}) {return <header className="rules-section-title"><span className="eyebrow">{number}</span><h2 className="type-heading-3">{children}</h2></header>;}
export default function RulesPage(){return <div className="home rules-site surface surface--primary"><SiteHeader homePrefix="/" /><main id="main"><Container>
<header className="rules-intro"><nav aria-label="Breadcrumb" className="rules-breadcrumb type-body-small"><Link href="/">Trang chủ</Link><span aria-hidden="true">/</span><span aria-current="page">Thể lệ</span></nav><div className="rules-title-row"><h1 className="type-display-l">Thể lệ</h1></div></header>
<div className="rules-layout"><aside><RulesNavigation /></aside><div className="rules-content">
<section id="gioi-thieu"><Title number="01">Giới thiệu chung</Title><p className="type-body-large">Travel Awards là giải thưởng thường niên về du lịch nhằm tôn vinh những điểm đến, doanh nghiệp và dịch vụ du lịch tiêu biểu của Việt Nam.</p><div className="rules-signature surface surface--brand-soft"><p className="eyebrow">The First Signature</p><h3 className="type-heading-3">Dấu ấn tiên phong</h3><p>Chủ đề của mùa giải đầu tiên Travel Awards, đánh dấu sự khởi đầu của hành trình tôn vinh những điểm đến, doanh nghiệp và cá nhân tiên phong đang kiến tạo những giá trị mới cho du lịch Việt Nam. Mỗi dấu ấn được ghi nhận không chỉ là thành tựu của hôm nay mà còn là nguồn cảm hứng cho sự phát triển bền vững của ngành trong tương lai.</p></div></section>
<section id="hang-muc"><Title number="02">Hạng mục & đối tượng tham gia</Title><p>Hệ thống gồm 15 hạng mục thuộc hai nhóm giải thưởng: Trụ cột và Tiên phong. Đối tượng tham gia được xác định theo từng hạng mục.</p>{groups.map((group,g)=><div className="rules-award-group" key={group.name}><h3 className="type-body-large">{group.name}<span>{group.awards.length} hạng mục</span></h3><ol>{group.awards.map((award,i)=><li key={award.name}><span className="rules-index">{String(i+1).padStart(2,'0')}</span><div><a href={'#criteria-'+g+'-'+i}>{award.name}<span aria-hidden="true"> ↗</span></a><p>{award.audience}</p></div></li>)}</ol></div>)}</section>
<section id="thoi-gian"><Title number="03">Thời gian tổ chức</Title><p>Các giai đoạn triển khai của mùa giải Travel Awards 2026.</p><ol className="rules-timeline">{phases.map(([month,title,copy],i)=><li key={title}><span className="rules-timeline-number">{String(i+1).padStart(2,'0')}</span><div><p className="eyebrow">{month}</p><h3 className="type-body-large">{title}</h3><p>{copy}</p></div></li>)}</ol></section>
<section id="tieu-chi"><Title number="04">Tiêu chí & phương thức đánh giá</Title><p>Mỗi hạng mục có bộ tiêu chí và tỷ trọng đánh giá riêng, kết hợp đánh giá của Hội đồng chuyên môn với khảo sát độc giả.</p><div className="rules-legend type-body-small"><span><i />Hội đồng chuyên môn</span><span><i />Khảo sát độc giả</span></div>{groups.map((group,g)=><div className="rules-criteria-group" key={group.name}><h3 className="type-body-large">{group.name}</h3>{group.awards.map((award,i)=><details id={'criteria-'+g+'-'+i} className="rules-criteria" key={award.name} open={g===0&&i===0}><summary><span className="rules-index">{String(i+1).padStart(2,'0')}</span><span>{award.name}</span><span className="rules-ratio">{award.expert} / {award.reader}</span><span className="rules-plus" aria-hidden="true">+</span></summary><div className="rules-criteria-body"><p>{award.description}</p><div className="rules-weights" aria-label={'Hội đồng chuyên môn '+award.expert+', khảo sát độc giả '+award.reader}><span style={{width:award.expert}}>{award.expert}</span><span style={{width:award.reader}}>{award.reader}</span></div><ul>{award.criteria.map(criterion=><li key={criterion}>{criterion}</li>)}</ul><Link className="text-link" href={'/dang-ky-de-cu?category='+ (g===0?'tru-cot':'tien-phong')+'-'+(i+1)}>Đề cử hạng mục này <span aria-hidden="true">↗</span></Link></div></details>)}</div>)}</section>
<section id="ho-so"><Title number="05">Hồ sơ đề cử</Title><p>Mỗi hồ sơ đăng ký cho một hạng mục. Trường hợp tham gia nhiều hạng mục, vui lòng thực hiện hồ sơ riêng cho từng hạng mục.</p><ol className="rules-dossier"><li><h3 className="type-body-large">Chọn hạng mục</h3><p>Xác định giải thưởng phù hợp với đối tượng và hoạt động của đơn vị hoặc cá nhân.</p></li><li><h3 className="type-body-large">Điền thông tin & minh chứng</h3><p>Cung cấp thông tin đăng ký, người đại diện, thông tin đề cử và các tài liệu theo yêu cầu trong biểu mẫu của từng hạng mục.</p></li><li><h3 className="type-body-large">Kiểm tra hồ sơ</h3><p>Rà soát thông tin và minh chứng tại bước xác nhận của biểu mẫu đề cử.</p></li></ol><NominationCTA /></section>
<section id="quy-dinh"><Title number="06">Điều lệ & quy định</Title><div className="rules-pending surface surface--brand-soft"><h3 className="type-body-large">Thông tin đang được cập nhật</h3><p>Các quy định chi tiết về tính hợp lệ của hồ sơ, bình chọn, bản quyền và xử lý khiếu nại sẽ được cập nhật khi Ban Tổ chức công bố.</p></div><p className="rules-contact">Giải đáp thông tin sự kiện: <a className="text-link" href="mailto:sukien@vnexpress.net">sukien@vnexpress.net</a></p></section>
</div></div></Container></main><SiteFooter homePrefix="/" /></div>;}

